# Airflow Helm Values
executor: "LocalExecutor"

airflow:
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"

serviceAccount:
  create: true
  name: airflow-sa

webserver:
  service:
    type: LoadBalancer

dags:
  gitSync:
    enabled: false
    # repo: https://github.com/janghyunwoo2/CALI.git
    # branch: main
    # subPath: dags
