# Grafana Helm Values (Optimized for OpenSearch Logging)
adminPassword: "admin"

# 1. Official Plugin Installation
plugins:
  - grafana-opensearch-datasource

# 2. Persistence (Data Survival)
persistence:
  enabled: true
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  finalizers:
    - kubernetes.io/pvc-protection

# 3. Security Context (Crucial for EBS)
securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472

# 4. Deployment Strategy
deploymentStrategy:
  type: Recreate

# 5. Service Exposure
service:
  type: LoadBalancer

# 6. Datasource Configuration
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: OpenSearch
        type: grafana-opensearch-datasource
        url: https://search-cali-logs-brzk65m2qt5mktujvcaz3inde4.ap-northeast-2.es.amazonaws.com
        access: proxy
        basicAuth: false
        isDefault: true
        jsonData:
          # [수정] @timestamp 대신 실제 인덱스의 필드명인 timestamp 사용
          timeField: "timestamp"
          version: "2.11.0"
          flavor: "opensearch"
          # [확인] 인덱스 패턴 뒤에 별표(*)가 포함되어야 합니다.
          database: "cali-logs*"
          sigV4Auth: true
          sigV4Region: "ap-northeast-2"

          # --- [추가] React #130 에러 해결 및 로그 시각화 설정 ---
          logMessageField: "message" # 전체 객체(_source) 대신 텍스트 메시지 필드 지정
          logLevelField: "level" # 로그 레벨(INFO, ERROR 등) 필드 지정
          pplEnabled: false # 초기 설정 안정성을 위해 PPL 비활성화 권장
          # --------------------------------------------------
          sigV4AuthType: "default" # Use IRSA (IAM Roles for Service Accounts)
