# Grafana Helm Values (Clean Standard Configuration)
adminPassword: "admin"

image:
  tag: "latest"

# 1. Official Plugin Installation
# Helm 차트가 시작 시 이 플러그인들을 자동으로 다운로드 및 설치합니다.
plugins:
  - grafana-opensearch-datasource

# 2. Persistence (Data Survival)
persistence:
  enabled: true
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  finalizers:
    - kubernetes.io/pvc-protection

# 3. Security Context (Crucial for EBS)
# EBS 볼륨에 대한 쓰기 권한을 보장하기 위해 fsGroup을 설정합니다.
securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472

# 4. Deployment Strategy
# RWO(EBS) 볼륨 충돌 방지를 위해 기존 Pod 종료 후 새 Pod 생성
deploymentStrategy:
  type: Recreate

# 5. Service Exposure
service:
  type: LoadBalancer

# 6. Datasource Configuration
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: OpenSearch2
        type: grafana-opensearch-datasource
        url: https://search-cali-logs-brzk65m2qt5mktujvcaz3inde4.ap-northeast-2.es.amazonaws.com
        access: proxy
        basicAuth: true
        basicAuthUser: admin
        secureJsonData:
          basicAuthPassword: "ChangeMe123!"
        isDefault: true
        jsonData:
          # 인덱스 필드명과 일치화
          timeField: "timestamp"
          version: "2.11.0"
          flavor: "opensearch"
          database: "cali-logs*"

          # 인증 설정 (IRSA 사용)
          sigV4Auth: true
          sigV4AuthType: "default"
          sigV4Region: "ap-northeast-2"

          # --- 로그 시각화 및 에러 방지 핵심 설정 ---
          logMessageField: "message" # [필수] _source 덩어리 대신 텍스트만 출력
          logLevelField: "level" # [필수] 로그 레벨 표시
          pplEnabled: false # [중요] React 에러 방지를 위해 PPL 비활성화
          includeFrozen: false # [추가] 검색 성능 최적화 및 에러 방지
