# Milvus Helm Values
# MVP용 최소 사양 설정 (Standalone 모드)

cluster:
  enabled: false

etcd:
  replicaCount: 1

pulsar:
  enabled: false

minio:
  mode: standalone

standalone:
  replicas: 1
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "0.5"
      memory: "1Gi"

attu:
  enabled: true
  ingress:
    enabled: false
