# Milvus Helm Values
# MVP용 최소 사양 설정 (Standalone 모드)

cluster:
  enabled: false

etcd:
  replicaCount: 1

pulsar:
  enabled: false

minio:
  mode: standalone

standalone:
  replicas: 1
  resources:
    limits:
      cpu: "1"
      memory: "1.2Gi"
    requests:
      cpu: "0.5"
      memory: "800Mi"

  persistence:
    enabled: true
    storageClass: "gp2"
    persistentVolumeClaim:
      existingClaim: ""

attu:
  enabled: true
  ingress:
    enabled: false
