apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-test
  namespace: default
  labels:
    app: ca-test
    type: autoscaler-test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ca-test
  template:
    metadata:
      labels:
        app: ca-test
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1Gi
